package com.fengjr.dev;
import java.util.Timer;  
import java.util.TimerTask;  

import org.testng.annotations.Test;

@Test
public class Timertest {
    
    public class M {  
        public void main() {  
            // TODO todo.generated by zoer  
            Timer timer = new Timer();  
            timer.schedule(new MyTask(), 1000, 2000);  
        }  
    }  
      
    class MyTask extends TimerTask {  
      
        @Override  
        public void run() {  
            System.out.println("dddd"); 
        }  
      
    }  
}
